up:
	docker-compose up -d

down:
	docker-compose down -v

restart:
	docker-compose down -v
	docker-compose up -d

superset_up:
	docker-compose -f ../superset/docker-compose-non-dev.yml up -d

superset_down:
	docker-compose -f ../superset/docker-compose-non-dev.yml down